services:
  streamy_db:
    image: postgres:16.2
    container_name: streamy_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=streamy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thisisasecretpassword
    ports:
      - '5430:5432'
    networks:
      - local
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'streamy']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 30s

  streamy_db_test:
    image: postgres:16.2
    container_name: streamy_db_test
    restart: no
    environment:
      - POSTGRES_DB=streamy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thisisasecretpassword
    ports:
      - '5431:5432'
    networks:
      - local
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'streamy']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 30s

  minio:
    container_name: streamy_minio
    image: minio/minio:RELEASE.2024-04-06T05-26-02Z
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - local
    ports:
      - '9002:9000'
      - '9003:9001'
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: streamyminioadmin
      MINIO_ROOT_PASSWORD: thisisasecretminiopassword
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  rmq:
    container_name: streamy_rmq
    image: rabbitmq:3.13.1-management
    hostname: rmq
    restart: unless-stopped
    networks:
      - local
    ports:
      - '5676:5672' # rmq port
      - '15677:15672' # management panel port
    volumes:
      - rmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: streamyrmq
      RABBITMQ_DEFAULT_PASS: thisisasecretrmqpassword
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  db_data:
    driver: local
  minio_data:
    driver: local
  rmq_data:
    driver: local

networks:
  local:
    driver: bridge
