on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
  workflow_dispatch:

env:
  BUILDER: 'heroku/builder:22'
  IMG_NAME: 'streamy:test'
  USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  dockerhub_remote_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set App Name
        run: 'echo "IMG_NAME=$(echo ${USERNAME})/$(echo ${IMG_NAME})" >> $GITHUB_ENV'

      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pack Remote Build
        uses: dfreilich/pack-action@v2.1.1
        with:
          args: 'build ${{ env.IMG_NAME }} --builder ${{ env.BUILDER }} --publish'

      - name: Test App
        run: |
          docker run -d -p 8080:3000 --name streamy ${{ env.IMG_NAME }}
          sleep 30s
          curl --request GET --url http://localhost:8080

      - name: Pack Rebase
        uses: dfreilich/pack-action@v2.1.1
        with:
          args: 'rebase ${{ env.IMG_NAME }}'

      - name: Inspect Image
        uses: dfreilich/pack-action@v2.1.1
        with:
          args: 'inspect-image ${{ env.IMG_NAME }}'

      - name: Clean Up
        run: |
          docker container stop 'personal-portfolio'
